force-app/main/default/objects/UserLicenseAllocation__c/UserLicenseAllocation__c.object-meta.xml
<CustomObject>
    <label>User License Allocation</label>
    <nameField>
        <displayFormat>ULA-{0}</displayFormat>
        <label>User License Allocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User License Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserLicenseAllocation__c/fields/AllocatedLicensePool__c.field-meta.xml
<CustomField>
    <fullName>AllocatedLicensePool__c</fullName>
    <label>Allocated License Pool</label>
    <referenceTo>License_Pool__c</referenceTo>
    <relationshipLabel>User License Allocations</relationshipLabel>
    <relationshipName>User_License_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserLicenseAllocation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>User License Allocations</relationshipLabel>
    <relationshipName>User_License_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserPoolAllocation__c/UserPoolAllocation__c.object-meta.xml
<CustomObject>
    <label>User Pool Allocation</label>
    <nameField>
        <displayFormat>UPA-{0}</displayFormat>
        <label>User Pool Allocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Pool Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserPoolAllocation__c/fields/LicensePool__c.field-meta.xml
<CustomField>
    <fullName>LicensePool__c</fullName>
    <label>License Pool</label>
    <referenceTo>License_Pool__c</referenceTo>
    <relationshipLabel>User Pool Allocations</relationshipLabel>
    <relationshipName>User_Pool_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserPoolAllocation__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>User Pool Allocations</relationshipLabel>
    <relationshipName>User_Pool_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserLicenseAllocationTriggerHelper.cls
public class UserLicenseAllocationTriggerHelper {
    
    public UserLicenseAllocationTriggerHelper() {
      //  System.debug('Inside AccountTriggerHelper Constructor');
    }

    public void updateUserPoolAllocationField(List<UserLicenseAllocation__c> newUserLicenseAllocations)
    {
        Set<Id> usersInScope = new Set<Id>();
        
        For(UserLicenseAllocation__c allocation : newUserLicenseAllocations)
        {
            usersInScope.add(allocation.User__c);
        }
        
        Map<Id, Id> userToPoolMappingsForAllocations = userToPoolMappings(usersInScope);
        
        For(UserLicenseAllocation__c allocation : newUserLicenseAllocations)
        {
            allocation.AllocatedLicensePool__c = userToPoolMappingsForAllocations.get(allocation.User__c);
        }
    }
    
    private static Map<Id, Id> userToPoolMappings(Set<Id> usersInScope)
    {
        Map<Id, Id> userToPoolMappings = new Map<Id,Id>();

        List<UserPoolAllocation__c> allocations = [SELECT Id, User__c, LicensePool__c FROM UserPoolAllocation__c WHERE User__c IN :usersInScope];
        
        for(UserPoolAllocation__c allocation : allocations)
        {
            userToPoolMappings.put(allocation.User__c, allocation.LicensePool__c);
        }
        return userToPoolMappings;
    }
}